# app/routes/plan.py
from fastapi import APIRouter, HTTPException, Depends, status, Body
from app.models import Plan, Task
from app.db import get_database
from motor.motor_asyncio import AsyncIOMotorDatabase
from typing import Literal, List
from app.agents.plan_agent import generate_plan_with_agent
from bson import ObjectId
from bson.errors import InvalidId
from datetime import datetime, timedelta
import json

router = APIRouter(prefix="/plan", tags=["Plan Generation"])

USER_COLLECTION = "users"
PLAN_COLLECTION = "plans"
TASK_COLLECTION = "tasks"

@router.post(
    "/generate", 
    response_model=Plan,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a new workout or diet plan"
)
async def generate_plan(
    db: AsyncIOMotorDatabase = Depends(get_database),
    user_id: str = Body(..., description="The ID of the user for whom to generate the plan."),
    plan_type: Literal["workout", "diet"] = Body(..., alias="type", description="The type of plan to generate.")
):
    """
    Generates a personalized plan, saves it, and creates individual daily tasks in the database.
    Requires `user_id` and `type` in the request body.
    """
    try:
        user_obj_id = ObjectId(user_id)
    except InvalidId:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Invalid user ID format: {user_id}")

    user_data = await db[USER_COLLECTION].find_one({"_id": user_obj_id})
    if not user_data:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"User with id {user_id} not found")

    # 1. Generate the plan content from the AI agent
    plan_json_string = await generate_plan_with_agent(user_data, plan_type)
    
    try:
        # 2. Parse the JSON string into a Python dictionary
        plan_content = json.loads(plan_json_string)
    except json.JSONDecodeError:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to parse the plan generated by the AI. The format was invalid."
        )

    # 3. Create and save the main Plan object
    now = datetime.utcnow()
    new_plan = Plan(
        user_id=user_id,
        type=plan_type,
        content=plan_content,
        created_at=now,
        updated_at=now
    )
    plan_dict = new_plan.model_dump(by_alias=True, exclude=["id"])
    result = await db[PLAN_COLLECTION].insert_one(plan_dict)
    plan_id = result.inserted_id

    # 4. Create individual Task documents from the plan content
    tasks_to_create = []
    plan_start_date = datetime.utcnow().date()

    if "daily_tasks" in plan_content and isinstance(plan_content["daily_tasks"], list):
        for day_plan in plan_content["daily_tasks"]:
            day_number = day_plan.get("day", 1) - 1 # Day 1 is index 0
            task_date = datetime.combine(plan_start_date + timedelta(days=day_number), datetime.min.time())
            
            if "tasks" in day_plan and isinstance(day_plan["tasks"], list):
                for task_desc in day_plan["tasks"]:
                    task = Task(
                        user_id=user_obj_id,
                        plan_id=plan_id,
                        task_date=task_date,
                        description=task_desc,
                        type=plan_type,
                    )
                    tasks_to_create.append(task.model_dump(by_alias=True, exclude=["id"]))
    
    if tasks_to_create:
        await db[TASK_COLLECTION].insert_many(tasks_to_create)

    # 5. Return the created Plan object
    created_plan = await db[PLAN_COLLECTION].find_one({"_id": plan_id})
    if created_plan is None:
         raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to create the plan."
        )

    return created_plan

@router.get(
    "/user/{user_id}",
    response_model=List[Plan],
    status_code=status.HTTP_200_OK,
    summary="Get all plans for a specific user"
)
async def get_plans_for_user(
    user_id: str,
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    """
    Retrieves all workout and diet plans that have been generated for a user,
    ordered by creation date.
    """
    try:
        user_obj_id = ObjectId(user_id)
    except InvalidId:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Invalid user ID format: {user_id}")

    # Find all plans for the given user_id and sort them from newest to oldest
    cursor = db[PLAN_COLLECTION].find({"user_id": user_obj_id}).sort("created_at", -1)
    
    plans = await cursor.to_list(length=None)
    
    return plans